@startuml
left to right direction
skinparam roundcorner 5
skinparam linetype ortho
skinparam shadowing false
skinparam handwritten false
skinparam class {
    BackgroundColor white
    ArrowColor #2688d4
    BorderColor #2688d4
}
skinparam legendBackgroundColor white

!define primary_key(name) <b><color:#b8861b><&key></color> name</b>
!define foreign_key(name) <color:#aaaaaa><&key></color> name
!define column(name) <color:#efefef><&media-record></color> name
!define table(logical, physical) entity "logical" as physical << (T, white) >>

'diagram title'
title Extract Load Batch Application - Logical Model

table( Extract Load Application Configuration Type, EL_APP_CONFIGURATION_TYPE ) {
  primary_key( Configuration Type Unique Identifier )
  --
  column( Configuration Type Name )
  column( Configuration Type Description )
  column( Create Date Time )
  column( Update Date Time )
}

table( Extract Load Application Property, EL_APP_PROPERTY ) {
  primary_key( Property Unique Identifier )
  --
  column( Property Key Name )
  column( Property Description )
  column( Create Date Time )
  column( Update Date Time )
}

table( Extract Load Application Configuration, EL_APP_CONFIGURATION ) {
  primary_key( Configuration Unique Identifier )
  --
  foreign_key( Configuration Type Unique Identifier )
  --
  column( Configuration Name )
  column( Configuration Description )
  column( Create Date Time )
  column( Update Date Time )
}

table( Extract Load Application Configuration Properties, EL_APP_CONFIGURATION_PROPERTIES ) {
  primary_key( Configuration Properties Unique Identifier )
  --
  foreign_key( Configuration Unique Identifier )
  foreign_key( Property Unique Identifier )
  --
  column( Property Value )
  column( Create Date Time )
  column( Update Date Time )
}

table( Extract Load Data Bundle, EL_DATA_BUNDLE ) {
  primary_key( Bundle Unique Identifier )
  --
  foreign_key( Source Configuration Properties Unique Identifier )
  foreign_key( Target Configuration Properties Unique Identifier )
  --
  column( Bundle Name )
  column( Create Date Time )
  column( Update Date Time )
}

table( Extract Load Table, EL_TABLE ) {
  primary_key( Table Unique Identifier )
  --
  column( Table Physical Name )
  column( Create Date Time )
  column( Update Date Time )
}

table( Extract Load Bundled Tables, EL_BUNDLED_TABLES ) {
  primary_key( Bundled Table Unique Identifier )
  --
  foreign_key( Bundle Unique Identifier )
  foreign_key( Source Table Unique Identifier )
  foreign_key( Target Table Unique Identifier )
  --
  column( Relational Ordering Number )
  column( Query Select )
  column( Query Insert )
  column( Query Update )
  column( Create Date Time )
  column( Update Date Time )
}

EL_APP_CONFIGURATION_TYPE ||--|{ EL_APP_CONFIGURATION
EL_APP_CONFIGURATION_PROPERTIES }|--|| EL_APP_CONFIGURATION
EL_APP_CONFIGURATION_PROPERTIES }|--|| EL_APP_PROPERTY

EL_DATA_BUNDLE }|--|| EL_APP_CONFIGURATION
EL_DATA_BUNDLE }|--|| EL_APP_CONFIGURATION
EL_BUNDLED_TABLES }|--|| EL_DATA_BUNDLE
EL_BUNDLED_TABLES }|--|| EL_TABLE
EL_BUNDLED_TABLES }|--|| EL_TABLE

legend left
    |= |= Type |
    | <b>T</b> | Table |
    | <color:#b8861b><&key></color> | Primary Key |
    | <color:#aaaaaa><&key></color> | Foreign Key |
    | <color:#efefef><&media-record></color> | Attribute |
endlegend

@enduml