-- Oracle DDL script for the SAMPLE_APP schema
-- From source: https://github.com/oracle-samples/db-sample-schemas/blob/main/customer_orders/

CREATE
USER SAMPLE_APP IDENTIFIED BY SAMPLE_APP;
ALTER
USER SAMPLE_APP QUOTA 524M ON SYSTEM;
GRANT UNLIMITED
TABLESPACE TO SAMPLE_APP;

ALTER
USER SAMPLE_APP DEFAULT TABLESPACE USERS
              QUOTA UNLIMITED ON USERS;

ALTER
USER SAMPLE_APP TEMPORARY TABLESPACE TEMP;

GRANT CREATE
SESSION,
CREATE TABLE,
CREATE SEQUENCE,
CREATE VIEW,
CREATE PROCEDURE
    TO SAMPLE_APP
  IDENTIFIED BY "SAMPLE_APP";

CREATE SEQUENCE SAMPLE_APP.CUSTOMERS_SEQ
    MINVALUE 1
    INCREMENT BY 1
    START WITH 1 CACHE 20
    NOCYCLE;

CREATE SEQUENCE SAMPLE_APP.STORES_SEQ
    MINVALUE 1
    INCREMENT BY 1
    START WITH 1 CACHE 20
    NOCYCLE;

CREATE SEQUENCE SAMPLE_APP.PRODUCTS_SEQ
    MINVALUE 1
    INCREMENT BY 1
    START WITH 1 CACHE 20
    NOCYCLE;

CREATE SEQUENCE SAMPLE_APP.ORDERS_SEQ
    MINVALUE 1
    INCREMENT BY 1
    START WITH 1 CACHE 20
    NOCYCLE;

CREATE SEQUENCE SAMPLE_APP.SHIPMENTS_SEQ
    MINVALUE 1
    INCREMENT BY 1
    START WITH 1 CACHE 20
    NOCYCLE;

CREATE SEQUENCE SAMPLE_APP.ORDER_ITEMS_SEQ
    MINVALUE 1
    INCREMENT BY 1
    START WITH 1 CACHE 20
    NOCYCLE;

CREATE SEQUENCE SAMPLE_APP.INVENTORY_SEQ
    MINVALUE 1
    INCREMENT BY 1
    START WITH 1 CACHE 20
    NOCYCLE;

CREATE TABLE SAMPLE_APP.CUSTOMERS
(
    CUSTOMER_ID      INTEGER,
    EMAIL_ADDRESS    VARCHAR2(255 CHAR) NOT NULL,
    FULL_NAME        VARCHAR2(255 CHAR) NOT NULL,
    CREATE_DATE_TIME TIMESTAMP(6) DEFAULT SYSDATE NOT NULL,
    UPDATE_DATE_TIME TIMESTAMP(6) DEFAULT SYSDATE NOT NULL
)
;

CREATE TABLE SAMPLE_APP.STORES
(
    STORE_ID          INTEGER,
    STORE_NAME        VARCHAR2(255 CHAR) NOT NULL,
    WEB_ADDRESS       VARCHAR2(100 CHAR),
    PHYSICAL_ADDRESS  VARCHAR2(512 CHAR),
    LATITUDE          NUMBER,
    LONGITUDE         NUMBER,
    LOGO              BLOB,
    LOGO_MIME_TYPE    VARCHAR2(512 CHAR),
    LOGO_FILENAME     VARCHAR2(512 CHAR),
    LOGO_CHARSET      VARCHAR2(512 CHAR),
    LOGO_LAST_UPDATED DATE,
    CREATE_DATE_TIME  TIMESTAMP(6) DEFAULT SYSDATE NOT NULL,
    UPDATE_DATE_TIME  TIMESTAMP(6) DEFAULT SYSDATE NOT NULL
)
;

CREATE TABLE SAMPLE_APP.PRODUCTS
(
    PRODUCT_ID         INTEGER,
    PRODUCT_NAME       VARCHAR2(255 CHAR) NOT NULL,
    UNIT_PRICE         NUMBER(10,2),
    PRODUCT_DETAILS    BLOB,
    PRODUCT_IMAGE      BLOB,
    IMAGE_MIME_TYPE    VARCHAR2(512 CHAR),
    IMAGE_FILENAME     VARCHAR2(512 CHAR),
    IMAGE_CHARSET      VARCHAR2(512 CHAR),
    IMAGE_LAST_UPDATED DATE,
    CREATE_DATE_TIME   TIMESTAMP(6) DEFAULT SYSDATE NOT NULL,
    UPDATE_DATE_TIME   TIMESTAMP(6) DEFAULT SYSDATE NOT NULL
)
;

CREATE TABLE SAMPLE_APP.ORDERS
(
    ORDER_ID         INTEGER,
    ORDER_DATETIME   TIMESTAMP                    NOT NULL,
    CUSTOMER_ID      INTEGER                      NOT NULL,
    ORDER_STATUS     VARCHAR2(10 CHAR) NOT NULL,
    STORE_ID         INTEGER                      NOT NULL,
    CREATE_DATE_TIME TIMESTAMP(6) DEFAULT SYSDATE NOT NULL,
    UPDATE_DATE_TIME TIMESTAMP(6) DEFAULT SYSDATE NOT NULL
)
;

CREATE TABLE SAMPLE_APP.SHIPMENTS
(
    SHIPMENT_ID      INTEGER,
    STORE_ID         INTEGER                      NOT NULL,
    CUSTOMER_ID      INTEGER                      NOT NULL,
    DELIVERY_ADDRESS VARCHAR2(512 CHAR) NOT NULL,
    SHIPMENT_STATUS  VARCHAR2(100 CHAR) NOT NULL,
    CREATE_DATE_TIME TIMESTAMP(6) DEFAULT SYSDATE NOT NULL,
    UPDATE_DATE_TIME TIMESTAMP(6) DEFAULT SYSDATE NOT NULL
)
;

CREATE TABLE SAMPLE_APP.ORDER_ITEMS
(
    ORDER_ITEM_ID    INTEGER                      NOT NULL,
    ORDER_ID         INTEGER                      NOT NULL,
    LINE_ITEM_ID     INTEGER                      NOT NULL,
    PRODUCT_ID       INTEGER                      NOT NULL,
    UNIT_PRICE       NUMBER(10,2) NOT NULL,
    QUANTITY         INTEGER                      NOT NULL,
    SHIPMENT_ID      INTEGER,
    CREATE_DATE_TIME TIMESTAMP(6) DEFAULT SYSDATE NOT NULL,
    UPDATE_DATE_TIME TIMESTAMP(6) DEFAULT SYSDATE NOT NULL
)
;

CREATE TABLE SAMPLE_APP.INVENTORY
(
    INVENTORY_ID      INTEGER,
    STORE_ID          INTEGER                      NOT NULL,
    PRODUCT_ID        INTEGER                      NOT NULL,
    PRODUCT_INVENTORY INTEGER                      NOT NULL,
    CREATE_DATE_TIME  TIMESTAMP(6) DEFAULT SYSDATE NOT NULL,
    UPDATE_DATE_TIME  TIMESTAMP(6) DEFAULT SYSDATE NOT NULL
)
;

CREATE INDEX SAMPLE_APP.CUSTOMERS_NAME_I ON SAMPLE_APP.CUSTOMERS (FULL_NAME);
CREATE INDEX SAMPLE_APP.ORDERS_CUSTOMER_ID_I ON SAMPLE_APP.ORDERS (CUSTOMER_ID);
CREATE INDEX SAMPLE_APP.ORDERS_STORE_ID_I ON SAMPLE_APP.ORDERS (STORE_ID);
CREATE INDEX SAMPLE_APP.SHIPMENTS_STORE_ID_I ON SAMPLE_APP.SHIPMENTS (STORE_ID);
CREATE INDEX SAMPLE_APP.SHIPMENTS_CUSTOMER_ID_I ON SAMPLE_APP.SHIPMENTS (CUSTOMER_ID);
CREATE INDEX SAMPLE_APP.ORDER_ITEMS_SHIPMENT_ID_I ON SAMPLE_APP.ORDER_ITEMS (SHIPMENT_ID);
CREATE INDEX SAMPLE_APP.INVENTORY_PRODUCT_ID_I ON SAMPLE_APP.INVENTORY (PRODUCT_ID);

ALTER TABLE SAMPLE_APP.CUSTOMERS
    ADD CONSTRAINT CUSTOMERS_PK PRIMARY KEY (CUSTOMER_ID);

ALTER TABLE SAMPLE_APP.CUSTOMERS
    ADD CONSTRAINT CUSTOMERS_EMAIL_U UNIQUE (EMAIL_ADDRESS);

ALTER TABLE SAMPLE_APP.STORES
    ADD CONSTRAINT STORES_PK PRIMARY KEY (STORE_ID);

ALTER TABLE SAMPLE_APP.STORES
    ADD CONSTRAINT STORE_NAME_U UNIQUE (STORE_NAME);

ALTER TABLE SAMPLE_APP.STORES
    ADD CONSTRAINT STORE_AT_LEAST_ONE_ADDRESS_C
        CHECK (
            WEB_ADDRESS IS NOT NULL OR PHYSICAL_ADDRESS IS NOT NULL
            );

ALTER TABLE SAMPLE_APP.PRODUCTS
    ADD CONSTRAINT PRODUCTS_PK PRIMARY KEY (PRODUCT_ID);

ALTER TABLE SAMPLE_APP.ORDERS
    ADD CONSTRAINT ORDERS_PK PRIMARY KEY (ORDER_ID);

ALTER TABLE SAMPLE_APP.ORDERS
    ADD CONSTRAINT ORDERS_CUSTOMER_ID_FK
        FOREIGN KEY (CUSTOMER_ID) REFERENCES SAMPLE_APP.CUSTOMERS (CUSTOMER_ID);

ALTER TABLE SAMPLE_APP.ORDERS
    ADD CONSTRAINT ORDERS_STATUS_C
        CHECK ( ORDER_STATUS IN
                ('CANCELLED', 'COMPLETE', 'OPEN', 'PAID', 'REFUNDED', 'SHIPPED'));

ALTER TABLE SAMPLE_APP.ORDERS
    ADD CONSTRAINT ORDERS_STORE_ID_FK FOREIGN KEY (STORE_ID)
        REFERENCES SAMPLE_APP.STORES (STORE_ID);

ALTER TABLE SAMPLE_APP.SHIPMENTS
    ADD CONSTRAINT SHIPMENTS_PK PRIMARY KEY (SHIPMENT_ID);

ALTER TABLE SAMPLE_APP.SHIPMENTS
    ADD CONSTRAINT SHIPMENTS_STORE_ID_FK
        FOREIGN KEY (STORE_ID) REFERENCES SAMPLE_APP.STORES (STORE_ID);

ALTER TABLE SAMPLE_APP.SHIPMENTS
    ADD CONSTRAINT SHIPMENTS_CUSTOMER_ID_FK
        FOREIGN KEY (CUSTOMER_ID) REFERENCES SAMPLE_APP.CUSTOMERS (CUSTOMER_ID);

ALTER TABLE SAMPLE_APP.SHIPMENTS
    ADD CONSTRAINT SHIPMENT_STATUS_C
        CHECK ( SHIPMENT_STATUS IN
                ('CREATED', 'SHIPPED', 'IN-TRANSIT', 'DELIVERED'));

ALTER TABLE SAMPLE_APP.ORDER_ITEMS
    ADD CONSTRAINT ORDER_ITEMS_PK PRIMARY KEY (ORDER_ITEM_ID);

ALTER TABLE SAMPLE_APP.ORDER_ITEMS
    ADD CONSTRAINT ORDER_ITEMS_ORDER_ID_FK
        FOREIGN KEY (ORDER_ID) REFERENCES SAMPLE_APP.ORDERS (ORDER_ID);

ALTER TABLE SAMPLE_APP.ORDER_ITEMS
    ADD CONSTRAINT ORDER_ITEMS_SHIPMENT_ID_FK
        FOREIGN KEY (SHIPMENT_ID) REFERENCES SAMPLE_APP.SHIPMENTS (SHIPMENT_ID);

ALTER TABLE SAMPLE_APP.ORDER_ITEMS
    ADD CONSTRAINT ORDER_ITEMS_PRODUCT_ID_FK
        FOREIGN KEY (PRODUCT_ID) REFERENCES SAMPLE_APP.PRODUCTS (PRODUCT_ID);

ALTER TABLE SAMPLE_APP.ORDER_ITEMS
    ADD CONSTRAINT ORDER_ITEMS_PRODUCT_U UNIQUE (PRODUCT_ID, ORDER_ID);

ALTER TABLE SAMPLE_APP.ORDER_ITEMS
    ADD CONSTRAINT ORDER_ITEMS_ORDER_U UNIQUE (ORDER_ID, LINE_ITEM_ID);

ALTER TABLE SAMPLE_APP.INVENTORY
    ADD CONSTRAINT INVENTORY_PK PRIMARY KEY (INVENTORY_ID);

ALTER TABLE SAMPLE_APP.INVENTORY
    ADD CONSTRAINT INVENTORY_STORE_PRODUCT_U UNIQUE (STORE_ID, PRODUCT_ID);

ALTER TABLE SAMPLE_APP.INVENTORY
    ADD CONSTRAINT INVENTORY_STORE_ID_FK
        FOREIGN KEY (STORE_ID) REFERENCES SAMPLE_APP.STORES (STORE_ID);

ALTER TABLE SAMPLE_APP.INVENTORY
    ADD CONSTRAINT INVENTORY_PRODUCT_ID_FK
        FOREIGN KEY (PRODUCT_ID) REFERENCES SAMPLE_APP.PRODUCTS (PRODUCT_ID);